app/Http/routes.php
<?php

// Home
Route::get('/', 'HomeController@index')->name('home');

// Invoice CRUD
Route::resource('/invoice', 'InvoiceController');
Route::get('/invoice/date/{id}', 'InvoiceController@dates')->name('invoice.dates');
Route::put('/invoice/date/{id}', 'InvoiceController@datesUpdate')->name('invoice.datesUpdate');
Route::get('/invoice/locale/{id}', 'InvoiceController@locale')->name('invoice.locale');
Route::post('/invoice/locale/{id}', 'InvoiceController@localeUpdate')->name('invoice.localeUpdate');
Route::post('/invoice/duplicate/{id}', 'InvoiceController@duplicate')->name('invoice.duplicate');

// invoice - finance
Route::get('/finance/show/{id}', 'FinanceController@show')->name('finance.show');
Route::get('/finance/date/{id}', 'FinanceController@dates')->name('finance.dates');
Route::put('/finance/date/{id}', 'FinanceController@datesUpdate')->name('finance.datesUpdate');

// Authentication routes
Route::get('login', 'Auth\AuthController@getLogin')->name('auth.login');
Route::post('login', 'Auth\AuthController@postLogin')->name('auth.login');
Route::get('logout', 'Auth\AuthController@getLogout')->name('auth.logout');

// Password reset link request routes.
Route::get('password/email', 'Auth\PasswordController@getEmail')->name('password.email');
Route::post('password/email', 'Auth\PasswordController@postEmail')->name('password.email');

// Password reset routes
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset')->name('reset');
Route::post('password/reset', 'Auth\PasswordController@postReset')->name('reset');

// Vessels routes
Route::resource('vessel', 'VesselController');

// RDAs routes
Route::resource('rda', 'RdaController');
Route::get('rda/json/{id}', 'RdaController@json')->name('rda.json');

// Targets routes
Route::resource('target', 'TargetController');
Route::get('target/chart', 'TargetController@chart')->name('target.chart');

// Agencies routes
Route::resource('agency', 'AgencyController');

// Ports routes
Route::resource('port', 'PortController');
Route::get('port/data/{id}', 'PortController@data')->name('port.data');

// Employers routes
Route::resource('employer', 'EmployerController');

// Vehicles routes
Route::resource('vehicle', 'VehicleController');

// Users routes
Route::get('user/password', 'UserController@editPassword')->name('user.editPassword');
Route::post('user/password', 'UserController@updatePassword')->name('user.updatePassword');
Route::get('user/activity', 'UserController@activity')->name('user.activity');
Route::get('user/registerActivity', 'UserController@registerActivity')->name('user.registerActivity');
Route::resource('user', 'UserController');

// Approval routes
Route::resource('approval', 'ApprovalController');
Route::get('approval/line-up/{id}', 'ApprovalController@lineUp')->name('approval.lineUp');
Route::get('approval/billing/{id}', 'ApprovalController@billing')->name('approval.billing');

// Billing routes
Route::resource('billing', 'BillingController');
Route::get('/billing/date/{id}', 'BillingController@dates')->name('billing.dates');
Route::put('/billing/date/{id}', 'BillingController@datesUpdate')->name('billing.datesUpdate');

// Historic routes
Route::resource('historic', 'HistoricController');
Route::get('/historic/pendingCost/{id}', 'HistoricController@pendingCost')->name('historic.pendingCost');
Route::post('/historic/commission/{id}', 'HistoricController@commission')->name('historic.commission');

// Supplied routes
Route::resource('supplied', 'SuppliedController');

// Settlement routes
Route::get('settlement', 'SettlementController@index')->name('settlement');

// Report routes
Route::get('report', 'ReportController@index')->name('report');

// Operational list routes
Route::get('programacao', 'OperationalController@index')->name('operational');

// Database backups route
Route::get('backup', 'BackupController@index')->name('backup');
Route::get('backup/{file}', 'BackupController@download')->name('backup.download');
Route::get('backup/mail/{file}', 'BackupController@sendMail')->name('backup.mail');

// alter line-up date
Route::get('config/lineup', 'ConfigController@lineup')->name('config.lineup');
Route::post('config/lineup', 'ConfigController@lineupPost')->name('config.lineupPost');

resources/views/footer.blade.php
<footer class="footer">
    <div class="container">
        <p class="text-muted text-center">
            <span class="white">SGCVS - Sistema de Gestão Comercial Vitória Ship. Desenvolvido por Popify. Versão 1.0.</span>
            <br>Reporte problemas tiago@tcosta.com.br ou (27) 99273-5492.
        </p>
    </div>
</footer>

resources/views/lineup-last-updated.blade.php
<div style="color:#fff; margin-top:-10px;">
    @if(isset($lineup->value))
        {{ Route::currentRouteName() == 'operational' ? 'Atualizado em' : 'Updated in' }}
         {{ Carbon\Carbon::parse($lineup->value)->format('d/m/Y H:i') }}
    @endif
    @can('update-lineup-date')
        <a href="{{ route('config.lineup') }}" class="iframe2 fancybox.iframe" style="color:#fff;">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>
    @endcan
</div>

resources/views/main.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="noindex" />
        <link rel="icon" href="/dist/images/favicon.ico">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
        <title>@yield('title')</title>

        <!-- build:css(public) css/all.css -->
        <link rel="stylesheet" href="/assets/css/bootstrap.css">
        <link rel="stylesheet" href="/assets/css/jquery-ui-1.10.0.custom.css" />
        <link rel="stylesheet" href="/assets/css/font-awesome.min.css" />
        <link rel="stylesheet" href="/assets/css/ie10-viewport-bug-workaround.css">
        <link rel="stylesheet" href="/assets/css/fancy/jquery.fancybox.css"/>
        <link rel="stylesheet" href="/assets/css/style.css">
        <link rel="stylesheet" href="/assets/css/dataTables.bootstrap.min.css"/>
        <link rel="stylesheet" href="/assets/css/buttons.bootstrap.min.css"/>
        <link rel="stylesheet" href="/assets/css/buttons.dataTables.min.css"/>
        <link rel="stylesheet" href="/assets/css/sweetalert.css"/>
        <link rel="stylesheet" href="/assets/js/select2/css/select2.min.css"/>
        <!-- endbuild -->
        <!--<link rel="stylesheet" href="/dist/css/all.css">-->

    </head>
    <body>

        <div class="loader"></div>

        @yield('navbar')

        @yield('content')

        <!-- build:js(public) js/all.js -->
        <script src="/assets/js/jquery.min.js"></script>
        <script src="/assets/js/bootstrap.min.js"></script>
        <script src="/assets/js/jquery-ui-1.10.0.custom.min.js"></script>
        <script src="/assets/js/jquery.mask.js"></script>
        <script src="/assets/css/fancy/jquery.fancybox.js"></script>
        <script src="/assets/js/sweetalert.min.js"></script>
        <script src="/assets/js/jquery.dataTables.min.js"></script>
        <script src="/assets/js/moment.min.js"></script>
        <script src="/assets/js/datetime-moment.js"></script>
        <script src="/assets/js/dataTables.bootstrap.min.js"></script>
        <script src="/assets/js/dataTables.buttons.min.js"></script>
        <script src="/assets/js/jszip.min.js"></script>
        <script src="/assets/js/pdfmake.min.js"></script>
        <script src="/assets/js/vfs_fonts.js"></script>
        <script src="/assets/js/buttons.html5.min.js"></script>
        <script src="/assets/js/buttons.print.min.js"></script>
        <script src="/assets/js/buttons.colVis.min.js"></script>
        <script src="/assets/js/jquery.maskMoney.min.js"></script>
        <script src="/assets/js/ie10-viewport-bug-workaround.js"></script>
        <script src="/assets/js/vue.min.js"></script>
        <script src="/assets/js/alerts.js"></script>
        <script src="/assets/js/vue-app.js?v=2"></script>
        <script src="/assets/js/select2/js/select2.full.min.js"></script>
        <script src="/assets/js/select2/js/i18n/pt-BR.js"></script>
        <script src="/assets/js/SGCVS.js?v=2"></script>
        <!-- endbuild -->

        <!--<script src="/dist/js/all.js"></script>-->
    </body>
</html>

resources/views/messages.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>We found some errors.</strong>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if($status)
    <div class="alert alert-info alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ $status }}
    </div>
@endif

resources/views/navbar.blade.php
@if(Auth::user()->group->id != 4)
    <nav class="navbar navbar-default navbar-fixed-top mod-nav">
        <div class="container-fluid bemvindo">
            <div class="col-xs-6">
                <span class="align-left">
                    <span>Welcome</span>
                    <strong>{{ Auth::user()->name }}</strong>
                </span>
            </div>
            <div class="col-xs-6">
                <span class="align-right">
                    <a class="loading" href="{{ route('auth.logout') }}">
                        <span class="glyphicon glyphicon-log-out"></span> Logout
                    </a>
                </span>
            </div>
        </div>
        <div class="container p-t1">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="loading" href="{{ route('home') }}" class="navbar-brand pad0">
                    <img class="img-responsive" src="/assets/images/logo.png" alt="Home">
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right mod-nav-r">
                    <li>
                        <a class="loading" href="{{ route('home') }}">
                            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                            <span>Line-up</span>
                        </a>
                    </li>
                    @can('supplied')
                        <li>
                            <a class="loading" href="{{ route('supplied.index') }}">
                                <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                                <span>Supplied</span>
                            </a>
                        </li>
                    @endcan

                    @can('approval')
                        <li>
                            <a class="loading" href="{{ route('approval.index') }}">
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                <span style="margin-right: 10px;">Approvals</span>
                                <div style="position: absolute; top:0; right:0;">
                                    @if($totalApprovalInvoices->totalInvoiceLs > 0)
                                        <span class="badge" style="background-color: red; display:block; font-size:10px; padding: 2px 4px;">{{ $totalApprovalInvoices->totalInvoiceLs }}</span>
                                    @else
                                        <span class="badge" style="background-color: white; color:white; display:block; font-size:10px; padding: 2px 4px;">0</span>
                                    @endif
                                    @if($totalApprovalInvoices->totalInvoiceBs > 0)
                                            <span class="badge" style="background-color: #29a329; font-size:10px; padding: 2px 4px;">{{ $totalApprovalInvoices->totalInvoiceBs }}</span>
                                    @endif
                                </div>
                            </a>
                        </li>
                    @endcan

                    @can('billing')
                        <li>
                            <a class="loading" href="{{ route('billing.index') }}">
                                <span class="glyphicon glyphicon-usd" aria-hidden="true"></span>
                                <span>Billing</span>
                            </a>
                        </li>
                    @endcan

                    @can('settlement')
                        <li>
                            <a class="loading" href="{{ route('settlement') }}">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                <span>Settlement</span>
                            </a>
                        </li>
                    @endcan

                    @can('historic')
                        <li>
                            <a class="loading" href="{{ route('historic.index') }}">
                                <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
                                <span>Historic</span>
                            </a>
                        </li>
                    @endcan

                    @can('records')
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Records
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                @can('vessel')
                                    <li>
                                        <a class="loading" href="{{ route('vessel.index') }}">VESSEL</a>
                                    </li>
                                @endcan
                                @can('rda')
                                    <li>
                                        <a class="loading" href="{{ route('rda.index') }}">R.D.A / CO-R.D.A</a>
                                    </li>
                                @endcan
                                @can('agency')
                                    <li>
                                        <a class="loading" href="{{ route('agency.index') }}">AGENCY</a>
                                    </li>
                                @endcan
                                @can('port')
                                    <li>
                                        <a class="loading" href="{{ route('port.index') }}">PORT</a>
                                    </li>
                                    <li role="separator" class="divider"></li>
                                @endcan
                                @can('employer')
                                    <li>
                                        <a class="loading" href="{{ route('employer.index') }}">EMPLOYER</a>
                                    </li>
                                @endcan
                                @can('vehicle')
                                    <li>
                                        <a class="loading" href="{{ route('vehicle.index') }}">VEHICLES</a>
                                    </li>
                                @endcan
                                @can('target')
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <a class="loading" href="{{ route('target.index') }}">TARGET</a>
                                    </li>
                                @endcan
                                @can('user')
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <a class="loading" href="{{ route('user.index') }}">USERS</a>
                                        <a class="loading" href="{{ route('user.activity') }}">USER ACTIVITY</a>
                                    </li>
                                @endcan
                                @can('databaseBackup')
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <a class="loading" href="{{ route('backup') }}">BACK-UPS</a>
                                    </li>
                                @endcan
                            </ul>
                        </li>
                    @endcan
                    @can('report')
                        <!--<li class="bar-vert"><a class="loading" href="{{ route('report') }}"><span class="glyphicon glyphicon-copy" aria-hidden="true"></span> Report</a></li>-->
                        <li class="bar-vert dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-copy" aria-hidden="true"></span> Report
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="loading" href="{{ route('report') }}">RESULTS</a>
                                </li>
                                <li>
                                    <a class="loading" href="{{ route('target.chart') }}">MONTHLY INDEX</a>
                                </li>
                            </ul>
                        </li>
                    @endcan

                    @can('create-invoice')
                        <li><a href="{{ route('invoice.create') }}" class="novo loading"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> New</a></li>
                    @endcan
                </ul>
            </div>
        </div>
    </nav>
@endif
<div class="container-fluid bg-sgcvs">
    <div class="container">
        <div class="col-sm-6 col-xs-12">
            @yield('module')
        </div>
        <div class="col-xs-6 hidden-xs">
            <h3 class="text-right white">{{ Auth::user()->locale->name }} <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span></h3>
        </div>
    </div>
</div>

resources/views/operational-updates.blade.php
<div class="panel panel-primary form-horizontal">
    <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#employers" aria-expanded="false">
      <h4 class="panel-title" aria-label="Click to open">Employers</h4>
    </div>
    <div id="employers" class="panel-collapse collapse" role="tabpanel">
      <div class="panel-body">
          <div class="form-group col-md-6">
              <label class="col-sm-3 control-label">Vehicle</label>
              <div class="col-sm-9">
                  <p class="form-control-static">{{ $invoice->vehicle ? $invoice->vehicle->plaque : '' }}</p>
              </div>
          </div>
          <div class="form-group col-md-6">
              <label class="col-sm-3 control-label">Emp. 1</label>
              <div class="col-sm-9">
                  <p class="form-control-static mb-0">{{ $invoice->employerOne ? $invoice->employerOne->name : '' }}</p>
              </div>
          </div>
          <div class="form-group col-md-6">
              <label class="col-sm-3 control-label">Emp. 2</label>
              <div class="col-sm-9">
                  <p class="form-control-static mb-0">{{ $invoice->employerTwo ? $invoice->employerTwo->name : '' }}</p>
              </div>
          </div>
          <div class="form-group col-md-6">
              <label class="col-sm-3 control-label">Emp. 3</label>
              <div class="col-sm-9">
                  <p class="form-control-static mb-0">{{ $invoice->employerThree ? $invoice->employerThree->name : '' }}</p>
              </div>
          </div>
      </div>
    </div>
</div>