app/Http/routes.php
<?php

// Home
Route::get('/', 'HomeController@index')->name('home');

// Invoice CRUD
Route::resource('/invoice', 'InvoiceController');
Route::get('/invoice/date/{id}', 'InvoiceController@dates')->name('invoice.dates');
Route::put('/invoice/date/{id}', 'InvoiceController@datesUpdate')->name('invoice.datesUpdate');
Route::get('/invoice/locale/{id}', 'InvoiceController@locale')->name('invoice.locale');
Route::post('/invoice/locale/{id}', 'InvoiceController@localeUpdate')->name('invoice.localeUpdate');
Route::post('/invoice/duplicate/{id}', 'InvoiceController@duplicate')->name('invoice.duplicate');

// invoice - finance
Route::get('/finance/show/{id}', 'FinanceController@show')->name('finance.show');
Route::get('/finance/date/{id}', 'FinanceController@dates')->name('finance.dates');
Route::put('/finance/date/{id}', 'FinanceController@datesUpdate')->name('finance.datesUpdate');

// Authentication routes
Route::get('login', 'Auth\AuthController@getLogin')->name('auth.login');
Route::post('login', 'Auth\AuthController@postLogin')->name('auth.login');
Route::get('logout', 'Auth\AuthController@getLogout')->name('auth.logout');

// Password reset link request routes.
Route::get('password/email', 'Auth\PasswordController@getEmail')->name('password.email');
Route::post('password/email', 'Auth\PasswordController@postEmail')->name('password.email');

// Password reset routes
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset')->name('reset');
Route::post('password/reset', 'Auth\PasswordController@postReset')->name('reset');

// Vessels routes
Route::resource('vessel', 'VesselController');

// RDAs routes
Route::resource('rda', 'RdaController');
Route::get('rda/json/{id}', 'RdaController@json')->name('rda.json');

// Targets routes
Route::resource('target', 'TargetController');
Route::get('target/chart', 'TargetController@chart')->name('target.chart');

// Agencies routes
Route::resource('agency', 'AgencyController');

// Ports routes
Route::resource('port', 'PortController');
Route::get('port/data/{id}', 'PortController@data')->name('port.data');

// Employers routes
Route::resource('employer', 'EmployerController');

// Vehicles routes
Route::resource('vehicle', 'VehicleController');

// Users routes
Route::get('user/password', 'UserController@editPassword')->name('user.editPassword');
Route::post('user/password', 'UserController@updatePassword')->name('user.updatePassword');
Route::get('user/activity', 'UserController@activity')->name('user.activity');
Route::get('user/registerActivity', 'UserController@registerActivity')->name('user.registerActivity');
Route::resource('user', 'UserController');

// Approval routes
Route::resource('approval', 'ApprovalController');
Route::get('approval/line-up/{id}', 'ApprovalController@lineUp')->name('approval.lineUp');
Route::get('approval/billing/{id}', 'ApprovalController@billing')->name('approval.billing');

// Billing routes
Route::resource('billing', 'BillingController');
Route::get('/billing/date/{id}', 'BillingController@dates')->name('billing.dates');
Route::put('/billing/date/{id}', 'BillingController@datesUpdate')->name('billing.datesUpdate');

// Historic routes
Route::resource('historic', 'HistoricController');
Route::get('/historic/pendingCost/{id}', 'HistoricController@pendingCost')->name('historic.pendingCost');
Route::post('/historic/commission/{id}', 'HistoricController@commission')->name('historic.commission');

// Supplied routes
Route::resource('supplied', 'SuppliedController');

// Settlement routes
Route::get('settlement', 'SettlementController@index')->name('settlement');

// Report routes
Route::get('report', 'ReportController@index')->name('report');

// Operational list routes
Route::get('programacao', 'OperationalController@index')->name('operational');

// Database backups route
Route::get('backup', 'BackupController@index')->name('backup');
Route::get('backup/{file}', 'BackupController@download')->name('backup.download');
Route::get('backup/mail/{file}', 'BackupController@sendMail')->name('backup.mail');

// alter line-up date
Route::get('config/lineup', 'ConfigController@lineup')->name('config.lineup');
Route::post('config/lineup', 'ConfigController@lineupPost')->name('config.lineupPost');

app/Models/Port.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Port extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'state_id', 'stevedore', 'boat', 'locale_id'];

    /**
     * Relationship with Invoice Model
     */
    public function invoice()
    {
        return $this->hasMany('App\Models\Invoice');
    }

    /**
     * Relationship with Invoice Model
     */
    public function state()
    {
        return $this->belongsTo('App\Models\State');
    }

    /**
     * Relationship with Invoice Locale
     */
    public function locale()
    {
        return $this->belongsTo('App\Models\Locale');
    }

    /**
     * Set value to uppercase
     */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtoupper($value);
    }
}

app/Http/Controllers/PortController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Models\Port;
use App\Models\State;
use Gate;

class PortController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::denies('port')) {
            return redirect(route('home'));
        }

        $ports  = Port::where('locale_id', '=', auth()->user()->locale_id)
                        ->orderBy('name', 'ASC')
                        ->paginate(50);

        $states = State::orderBy('abbr', 'ASC')->get();

        return view('port.index', compact('ports', 'states'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\Port\StorePortRequest $request, Port $port)
    {
        if (Gate::denies('port')) {
            return redirect(route('home'));
        }

        $port->fill($request->only('name', 'state_id', 'stevedore', 'boat'));
        $port->locale_id = auth()->user()->locale_id;
        $port->save();

        return redirect(route('port.index'))->with('status', 'Port saved with success.');
        ;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int                       $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::denies('port')) {
            return redirect(route('home'));
        }

        $port   = Port::findOrFail($id);
        $states = State::orderBy('abbr', 'ASC')->get();

        return view('port.edit', compact('port', 'states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int                       $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\Port\StorePortRequest $request, $id)
    {
        if (Gate::denies('port')) {
            return redirect(route('home'));
        }

        $port = Port::findOrFail($id);

        $port->fill($request->only('name', 'state_id', 'stevedore', 'boat'))->save();

        return redirect()->back()->with('status', 'Port updated with success.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int                       $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Requests\Port\DeletePortRequest $request, $id)
    {
        if (Gate::denies('port')) {
            return redirect(route('home'));
        }

        $port = Port::findOrFail($id);

        $port->delete();

        return redirect()->back()->with('status', 'Port deleted with success.');
    }

    /**
     * Return if the port has Steavedore and/or Boat
     *
     * @param  int                       $id
     * @return \Illuminate\Http\Response
     */
    public function data($id)
    {
        if (!\Request::ajax()) {
            return redirect(route('home'));
        }

        $port = Port::findOrFail($id);
        $data = [
            'boat'      => $port->boat,
            'stevedore' => $port->stevedore,
        ];

        return $data;
    }
}

resources/views/port/edit.blade.php
@extends('main')

@section('title', 'Edit Agency')

@section('content')

    <div class="container p-t1">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row form-horizontal">
                <form action="{{ route('port.update', $port->id) }}" method="post">
                    {!! csrf_field() !!}
                    <input name="_method" type="hidden" value="PUT">
                    <div class="col-sm-4">
                        @include('messages')
                        <div class="form-group row">
                            <label for="nome_port" class="col-sm-4 control-label"><span class= "red">*</span> Name</label>
                            <div class="col-sm-8">
                                <input name="name" type="text" class="form-control" value="{{ $port->name }}" uppercase>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 p-t4">
                        <div class="form-group row">
                            <label for="uf" class="col-sm-5 control-label"><span class= "red">*</span> UF</label>
                            <div class="col-sm-7">
                                <select name="state_id" class="form-control">
                                    @foreach($states as $state)
                                        <option value="{{ $state->id }}" {{ ($port->state_id == $state->id ? "selected":"") }}>{{ $state->abbr }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 p-t4">
                        <div class="form-group row">
                            <label for="estiva" class="col-sm-2 control-label"><span class= "red">*</span> Stevedore</label>
                            <div class="col-sm-4">
                                <select name="stevedore" class="form-control">
                                    <option value="1" {{ ($port->stevedore == 1 ? "selected":"") }}>YES</option>
                                    <option value="0" {{ ($port->stevedore == 0 ? "selected":"") }}>NO</option>
                                </select>
                            </div>
                            <label for="tem_lancha" class="col-sm-2 control-label p-t5"><span class= "red">*</span> Boat</label>
                            <div class="col-sm-4 ">
                                <select name="boat" class="form-control">
                                    <option value="1" {{ ($port->boat == 1 ? "selected":"") }}>YES</option>
                                    <option value="0" {{ ($port->boat == 0 ? "selected":"") }}>NO</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <input class="btn btn-primary loading" type="submit" value="SAVE" >
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">document.getElementsByTagName('body')[0].className+='nopad'</script>

@endsection

resources/views/port/index.blade.php
@extends('main')

@section('title', 'Port | SGCVS - Sistema de Gestão Comercial Vitória Ship')

@section('navbar')

    @section('module')
        <h3 class="white">
            <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Records
            <span class="font-l">/ Port</span>
        </h3>
    @endsection

    @include('navbar')

@endsection

@section('content')

    <div class="container p-t1">
        @include('messages')
        <div class="panel panel-default">
            <form action="{{ route('port.store') }}" method="post">
            {!! csrf_field() !!}
            <div class="panel-body p-t7">
                <div class="row form-horizontal">
                    <div class="col-sm-3">
                        <div class="form-group row">
                            <label for="name" class="col-sm-4 control-label">
                                <span class= "red">*</span> Name
                            </label>
                            <div class="col-sm-8">
                                <input name="name" type="text" class="form-control" value="{{ old('name') }}" uppercase>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2 p-t4">
                        <div class="form-group row">
                            <label for="state_id" class="col-sm-5 control-label"><span class= "red">*</span> UF</label>
                            <div class="col-sm-7">
                                <select name="state_id" class="form-control">
                                    @foreach($states as $state)
                                        <option value="{{ $state->id }}">{{ $state->abbr }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 p-t4">
                        <div class="form-group row">
                            <label for="stevedore" class="col-sm-6 control-label">
                                <span class= "red">*</span> Stevedore
                            </label>
                            <div class="col-sm-6">
                                <select name="stevedore" class="form-control">
                                    <option value="1">YES</option>
                                    <option value="0">NO</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2 p-t4">
                        <div class="form-group row">
                            <label for="boat" class="col-sm-5 control-label">
                                <span class= "red">*</span> Boat
                            </label>
                            <div class="col-sm-7">
                                <select name="boat" class="form-control">
                                    <option value="1">YES</option>
                                    <option value="0">NO</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <input class="btn btn-primary btn-block loading" type="submit" value="SAVE">
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
    <div class="container">
        <div class="table-responsive">
            <table class="table table-bordered table-condensed table-hover data-table">
                <thead>
                    <tr class="active">
                        <th>Name</th>
                        <th>UF</th>
                        <th>Stevedore</th>
                        <th>Boat</th>
                        <th class="opcoes">Options</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($ports as $port)
                    <tr>
                        <td>{{ $port->name }}</td>
                        <td>{{ $port->state->abbr }}</td>
                        <td>{{ ($port->stevedore == 1 ? "YES":"NO") }}</td>
                        <td>{{ ($port->boat == 1 ? "YES":"NO") }}</td>
                        <td>
                            <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                <div class="btn-group btn-group-xs" role="group">
                                    <a href="{{ route('port.edit', $port->id) }}" class="btn btn-default iframe fancybox.iframe border-right-n">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </a>
                                </div>
                                <div class="btn-group btn-group-xs" role="group">
                                    <a href="{{ route('port.destroy', $port->id) }}" class="btn btn-default"
                                        data-token="{{ csrf_token() }}"
                                        data-request=""
                                        data-title="Are you sure?"
                                        data-message="Are you sure that you want delete the port {{ $port->name }}?"
                                        data-button-text="Yes, delete it!">
                                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div>Showing {!! $ports->count() !!} of {!! $ports->total() !!} results</div>
            {!! $ports->render() !!}
        </div>
    </div>

@include('footer')

@endsection