app/Http/routes.php
<?php

// Home
Route::get('/', 'HomeController@index')->name('home');

// Invoice CRUD
Route::resource('/invoice', 'InvoiceController');
Route::get('/invoice/date/{id}', 'InvoiceController@dates')->name('invoice.dates');
Route::put('/invoice/date/{id}', 'InvoiceController@datesUpdate')->name('invoice.datesUpdate');
Route::get('/invoice/locale/{id}', 'InvoiceController@locale')->name('invoice.locale');
Route::post('/invoice/locale/{id}', 'InvoiceController@localeUpdate')->name('invoice.localeUpdate');
Route::post('/invoice/duplicate/{id}', 'InvoiceController@duplicate')->name('invoice.duplicate');

// invoice - finance
Route::get('/finance/show/{id}', 'FinanceController@show')->name('finance.show');
Route::get('/finance/date/{id}', 'FinanceController@dates')->name('finance.dates');
Route::put('/finance/date/{id}', 'FinanceController@datesUpdate')->name('finance.datesUpdate');

// Authentication routes
Route::get('login', 'Auth\AuthController@getLogin')->name('auth.login');
Route::post('login', 'Auth\AuthController@postLogin')->name('auth.login');
Route::get('logout', 'Auth\AuthController@getLogout')->name('auth.logout');

// Password reset link request routes.
Route::get('password/email', 'Auth\PasswordController@getEmail')->name('password.email');
Route::post('password/email', 'Auth\PasswordController@postEmail')->name('password.email');

// Password reset routes
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset')->name('reset');
Route::post('password/reset', 'Auth\PasswordController@postReset')->name('reset');

// Vessels routes
Route::resource('vessel', 'VesselController');

// RDAs routes
Route::resource('rda', 'RdaController');
Route::get('rda/json/{id}', 'RdaController@json')->name('rda.json');

// Targets routes
Route::resource('target', 'TargetController');
Route::get('target/chart', 'TargetController@chart')->name('target.chart');

// Agencies routes
Route::resource('agency', 'AgencyController');

// Ports routes
Route::resource('port', 'PortController');
Route::get('port/data/{id}', 'PortController@data')->name('port.data');

// Employers routes
Route::resource('employer', 'EmployerController');

// Vehicles routes
Route::resource('vehicle', 'VehicleController');

// Users routes
Route::get('user/password', 'UserController@editPassword')->name('user.editPassword');
Route::post('user/password', 'UserController@updatePassword')->name('user.updatePassword');
Route::get('user/activity', 'UserController@activity')->name('user.activity');
Route::get('user/registerActivity', 'UserController@registerActivity')->name('user.registerActivity');
Route::resource('user', 'UserController');

// Approval routes
Route::resource('approval', 'ApprovalController');
Route::get('approval/line-up/{id}', 'ApprovalController@lineUp')->name('approval.lineUp');
Route::get('approval/billing/{id}', 'ApprovalController@billing')->name('approval.billing');

// Billing routes
Route::resource('billing', 'BillingController');
Route::get('/billing/date/{id}', 'BillingController@dates')->name('billing.dates');
Route::put('/billing/date/{id}', 'BillingController@datesUpdate')->name('billing.datesUpdate');

// Historic routes
Route::resource('historic', 'HistoricController');
Route::get('/historic/pendingCost/{id}', 'HistoricController@pendingCost')->name('historic.pendingCost');
Route::post('/historic/commission/{id}', 'HistoricController@commission')->name('historic.commission');

// Supplied routes
Route::resource('supplied', 'SuppliedController');

// Settlement routes
Route::get('settlement', 'SettlementController@index')->name('settlement');

// Report routes
Route::get('report', 'ReportController@index')->name('report');

// Operational list routes
Route::get('programacao', 'OperationalController@index')->name('operational');

// Database backups route
Route::get('backup', 'BackupController@index')->name('backup');
Route::get('backup/{file}', 'BackupController@download')->name('backup.download');
Route::get('backup/mail/{file}', 'BackupController@sendMail')->name('backup.mail');

// alter line-up date
Route::get('config/lineup', 'ConfigController@lineup')->name('config.lineup');
Route::post('config/lineup', 'ConfigController@lineupPost')->name('config.lineupPost');

app/Models/Rda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Rda extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'type', 'payment_terms', 'discount_1', 'discount_2'];

    /**
     * Relationship with Invoice Model
     */
    public function invoice()
    {
        return $this->hasMany('App\Models\Invoice');
    }

    /**
     * Only user of group 1 and 2 can see the RDA/cord
     * name, another ones just see "SIGN" or "COB"
     */
    public function getNameAttribute($value)
    {
        if (in_array(auth()->user()->group->id, [1, 2, 5]))
        {
            return $value;
        }

        return $this->attributes['type'] == 1 ? 'SIGN' : 'COB';
    }

    /**
     * Set value to uppercase
     */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtoupper($value);
    }

    public function setEmailAttribute($value)
    {
        $this->attributes['email'] = strtolower($value);
    }
}

app/Http/Controllers/RdaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Models\Rda;
use Gate;

class RdaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::denies('rda')) {
            return redirect(route('home'));
        }

        $rdas = Rda::orderBy('name', 'ASC')->paginate(50);

        return view('rda.index')->with('rdas', $rdas);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\Rda\StoreRdaRequest $request)
    {
        if (Gate::denies('rda')) {
            return redirect(route('home'));
        }

        $rda = new Rda;

        $rda->create($request->all());

        return redirect(route('rda.index'))->with('status', 'Rda saved with success.');
        ;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int                       $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::denies('rda')) {
            return redirect(route('home'));
        }

        $rda = Rda::findOrFail($id);

        return view('rda.edit')->with('rda', $rda);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int                       $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\Rda\StoreRdaRequest $request, $id)
    {
        if (Gate::denies('rda')) {
            return redirect(route('home'));
        }

        $rda = Rda::findOrFail($id);

        $rda->fill($request->all())->save();

        return redirect()->back()->with('status', 'RDA/CO-RDA updated with success.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int                       $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Requests\Rda\DeleteRdaRequest $request, $id)
    {
        if (Gate::denies('rda')) {
            return redirect(route('home'));
        }

        $rda = Rda::findOrFail($id);

        $rda->delete();

        return redirect()->back()->with('status', 'RDA/CO-RDA deleted with success.');
    }

    public function json($id)
    {
        $rda = Rda::findOrFail($id);

        if ($rda->discount_1) {
            $discount_1 = 1 - ($rda->discount_1 / 100);
        } else {
            $discount_1 = null;
        }

        if ($rda->discount_2) {
            $discount_2 = 1 - ($rda->discount_2 / 100);
        } else {
            $discount_2 = null;
        }

        return [
            'payment_terms' => $rda->payment_terms,
            // precisa retornar % como fator de multiplicação,
            // ex: 5% = 0.95
            // ex: 30% = 0.70
            // ex: 100% = 0
            'discount_1' => $discount_1,
            'discount_2' => $discount_2,
        ];
    }
}

resources/views/rda/edit.blade.php
@extends('main')

@section('title', 'Edit RDA/CO-RDA')

@section('content')

<div class="container p-t1">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row form-horizontal">
            <form action="{{ route('rda.update', $rda->id) }}" method="post">
                {!! csrf_field() !!}
                <input name="_method" type="hidden" value="PUT">
                <div class="col-sm-5">
                    @include('messages')
                    <div class="col-sm-4">
                        <div class="form-group row">
                            <label for="nome_rda" class="col-sm-4 control-label">
                                <span class= "red">*</span> Name
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="name" value="{{ $rda->name }}" maxlength="45">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 p-t4">
                        <div class="form-group row">
                            <label for="email_rda" class="col-sm-5 control-label">
                                <span class= "red">*</span> E-mail
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="email" value="{{ $rda->email }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 p-t4">
                        <div class="form-group row">
                            <label for="tipo_rda" class="col-sm-5 control-label">
                                <span class= "red">*</span> Type
                            </label>
                            <div class="col-sm-7">
                                <select name="type" class="form-control">
                                    <option value="1" {{ ($rda->type == 1 ? "selected":"") }}>SIGN</option>
                                    <option value="0" {{ ($rda->type == 0 ? "selected":"") }}>COB</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-3 p-t4">
                        <div class="form-group row">
                            <label for="payment_terms" class="col-sm-5 control-label">
                                Payment Terms
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="payment_terms" value="{{ $rda->payment_terms }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 p-t4">
                        <div class="form-group row">
                            <label for="discount_1" class="col-sm-5 control-label">
                                Discount 1
                            </label>
                            <div class="col-sm-7">
                                <select name="discount_1" class="form-control">
                                    <option value="0" selected>No discount 0%</option>
                                    @for($i=5; $i <= 30; $i += 5)
                                        <option value="{{ $i }}">{{ $i }}%</option>
                                    @endfor
                                    <option disabled>-----------------------</option>
                                    @for($i=1; $i <= 30; $i++)
                                        @if($rda->discount_1 == $i)
                                            <option value="{{ $i }}" selected="selected">{{ $i }}%</option>
                                        @else
                                            <option value="{{ $i }}">{{ $i }}%</option>
                                        @endif
                                    @endfor
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 p-t4">
                        <div class="form-group row">
                            <label for="discount_2" class="col-sm-5 control-label">
                                Discount 2
                            </label>
                            <div class="col-sm-7">
                                <select name="discount_2" class="form-control">
                                    <option value="0" selected>No discount 0%</option>
                                    @for($i=5; $i <= 30; $i += 5)
                                        <option value="{{ $i }}">{{ $i }}%</option>
                                    @endfor
                                    <option disabled>-----------------------</option>
                                    @for($i=1; $i <= 30; $i++)
                                        @if($rda->discount_2 == $i)
                                            <option value="{{ $i }}" selected="selected">{{ $i }}%</option>
                                        @else
                                            <option value="{{ $i }}">{{ $i }}%</option>
                                        @endif
                                    @endfor
                                </select>
                            </div>
                        </div>
                    </div>


                    <div class="col-sm-2">
                        <input class="btn btn-primary loading" type="submit" value="SAVE" >
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>

<script type="text/javascript">document.getElementsByTagName('body')[0].className+='nopad'</script>

@endsection

resources/views/rda/index.blade.php
@extends('main')

@section('title', 'RDA/CO-RDA | SGCVS - Sistema de Gestão Comercial Vitória Ship')

@section('navbar')

    @section('module')
        <h3 class="white">
            <span class="glyphicon glyphicon-floppy-save" aria-hidden="true">
            </span> Records <span class="font-l">/ R.D.A e CO-R.D.A</span>
        </h3>
    @endsection

    @include('navbar')

@endsection

@section('content')

    <div class="container p-t1">
        @include('messages')
        <div class="panel panel-default">
            <form action="{{ route('rda.store') }}" method="post">
            {!! csrf_field() !!}
                <div class="panel-body p-t7">
                    <div class="row form-horizontal p-t4">
                        <div class="col-sm-6">
                            <div class="form-group row">
                                <label for="name" class="col-sm-3 control-label">
                                    <span class="red">*</span> Name
                                </label>
                                <div class="col-sm-9">
                                    <input name="name" type="text" class="form-control" value="{{ old('name') }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="email" class="col-sm-3 control-label">E-mail</label>
                                <div class="col-sm-9">
                                    <input name="email" type="text" class="form-control" value="{{ old('email') }}">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="discount_1" class="col-sm-3 control-label">Discount 1</label>
                                <div class="col-sm-9">
                                    <select name="discount_1" class="form-control">
                                        <option value="0" selected>No discount 0%</option>
                                        @for($i=5; $i <= 30; $i += 5)
                                            <option value="{{ $i }}">{{ $i }}%</option>
                                        @endfor
                                        <option disabled>-----------------------</option>
                                        @for($i=1; $i <= 30; $i++)
                                            <option value="{{ $i }}">{{ $i }}%</option>
                                        @endfor
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group row">
                                <label for="type" class="col-sm-3 control-label">Type</label>
                                <div class="col-sm-9">
                                    <select name="type" class="form-control">
                                        <option value="1">SIGN</option>
                                        <option value="0">COB</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="payment_terms" class="col-sm-3 control-label">Payment Terms</label>
                                <div class="col-sm-9">
                                    <input name="payment_terms" type="number" class="form-control" value="{{ old('payment_terms') }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="discount_2" class="col-sm-3 control-label">Discount 2</label>
                                <div class="col-sm-9">
                                    <select name="discount_2" class="form-control">
                                        <option value="0" selected>No discount 0%</option>
                                        @for($i=5; $i <= 30; $i += 5)
                                            <option value="{{ $i }}">{{ $i }}%</option>
                                        @endfor
                                        <option disabled>-----------------------</option>
                                        @for($i=1; $i <= 30; $i++)
                                            <option value="{{ $i }}">{{ $i }}%</option>
                                        @endfor
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2 col-md-offset-10 col-xs-12">
                            <input class="btn btn-primary btn-block loading" type="submit" value="SAVE" >
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="container">
        <div class="table-responsive">
            <table class="table table-bordered table-condensed table-hover data-table">
                <thead>
                    <tr class="active">
                        <th>Name</th>
                        <th>E-mail</th>
                        <th>Type</th>
                        <th>Disc. 1</th>
                        <th>Disc. 2</th>
                        <th>Payment Terms</th>
                        <th class="opcoes">Options</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($rdas as $rda)
                    <tr>
                        <td>{{ $rda->name }}</td>
                        <td>{{ $rda->email }}</td>
                        <td>{{ ($rda->type == 1 ? "SIGN":"COB") }}</td>
                        <td align="center">{{ (float) $rda->discount_1 }}%</td>
                        <td align="center">{{ (float) $rda->discount_2 }}%</td>
                        <td>{{ $rda->payment_terms }}</td>
                        <td>
                            <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                <div class="btn-group btn-group-xs" role="group">
                                    <a href="{{ route('rda.edit', $rda->id) }}" class="btn btn-default iframe2 fancybox.iframe border-right-n">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </a>
                                </div>
                                <div class="btn-group btn-group-xs" role="group">
                                    <a href="{{ route('rda.destroy', $rda->id) }}" class="btn btn-default"
                                        data-token="{{ csrf_token() }}"
                                        data-request=""
                                        data-title="Are you sure?"
                                        data-message="Are you sure that you want delete {{ $rda->name }}?"
                                        data-button-text="Yes, delete it!">
                                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div>Showing {!! $rdas->count() !!} of {!! $rdas->total() !!} results</div>
            {!! $rdas->render() !!}
        </div>
    </div>

@include('footer')

@endsection