app/Http/routes.php
<?php

// Home
Route::get('/', 'HomeController@index')->name('home');

// Invoice CRUD
Route::resource('/invoice', 'InvoiceController');
Route::get('/invoice/date/{id}', 'InvoiceController@dates')->name('invoice.dates');
Route::put('/invoice/date/{id}', 'InvoiceController@datesUpdate')->name('invoice.datesUpdate');
Route::get('/invoice/locale/{id}', 'InvoiceController@locale')->name('invoice.locale');
Route::post('/invoice/locale/{id}', 'InvoiceController@localeUpdate')->name('invoice.localeUpdate');
Route::post('/invoice/duplicate/{id}', 'InvoiceController@duplicate')->name('invoice.duplicate');

// invoice - finance
Route::get('/finance/show/{id}', 'FinanceController@show')->name('finance.show');
Route::get('/finance/date/{id}', 'FinanceController@dates')->name('finance.dates');
Route::put('/finance/date/{id}', 'FinanceController@datesUpdate')->name('finance.datesUpdate');

// Authentication routes
Route::get('login', 'Auth\AuthController@getLogin')->name('auth.login');
Route::post('login', 'Auth\AuthController@postLogin')->name('auth.login');
Route::get('logout', 'Auth\AuthController@getLogout')->name('auth.logout');

// Password reset link request routes.
Route::get('password/email', 'Auth\PasswordController@getEmail')->name('password.email');
Route::post('password/email', 'Auth\PasswordController@postEmail')->name('password.email');

// Password reset routes
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset')->name('reset');
Route::post('password/reset', 'Auth\PasswordController@postReset')->name('reset');

// Vessels routes
Route::resource('vessel', 'VesselController');

// RDAs routes
Route::resource('rda', 'RdaController');
Route::get('rda/json/{id}', 'RdaController@json')->name('rda.json');

// Targets routes
Route::resource('target', 'TargetController');
Route::get('target/chart', 'TargetController@chart')->name('target.chart');

// Agencies routes
Route::resource('agency', 'AgencyController');

// Ports routes
Route::resource('port', 'PortController');
Route::get('port/data/{id}', 'PortController@data')->name('port.data');

// Employers routes
Route::resource('employer', 'EmployerController');

// Vehicles routes
Route::resource('vehicle', 'VehicleController');

// Users routes
Route::get('user/password', 'UserController@editPassword')->name('user.editPassword');
Route::post('user/password', 'UserController@updatePassword')->name('user.updatePassword');
Route::get('user/activity', 'UserController@activity')->name('user.activity');
Route::get('user/registerActivity', 'UserController@registerActivity')->name('user.registerActivity');
Route::resource('user', 'UserController');

// Approval routes
Route::resource('approval', 'ApprovalController');
Route::get('approval/line-up/{id}', 'ApprovalController@lineUp')->name('approval.lineUp');
Route::get('approval/billing/{id}', 'ApprovalController@billing')->name('approval.billing');

// Billing routes
Route::resource('billing', 'BillingController');
Route::get('/billing/date/{id}', 'BillingController@dates')->name('billing.dates');
Route::put('/billing/date/{id}', 'BillingController@datesUpdate')->name('billing.datesUpdate');

// Historic routes
Route::resource('historic', 'HistoricController');
Route::get('/historic/pendingCost/{id}', 'HistoricController@pendingCost')->name('historic.pendingCost');
Route::post('/historic/commission/{id}', 'HistoricController@commission')->name('historic.commission');

// Supplied routes
Route::resource('supplied', 'SuppliedController');

// Settlement routes
Route::get('settlement', 'SettlementController@index')->name('settlement');

// Report routes
Route::get('report', 'ReportController@index')->name('report');

// Operational list routes
Route::get('programacao', 'OperationalController@index')->name('operational');

// Database backups route
Route::get('backup', 'BackupController@index')->name('backup');
Route::get('backup/{file}', 'BackupController@download')->name('backup.download');
Route::get('backup/mail/{file}', 'BackupController@sendMail')->name('backup.mail');

// alter line-up date
Route::get('config/lineup', 'ConfigController@lineup')->name('config.lineup');
Route::post('config/lineup', 'ConfigController@lineupPost')->name('config.lineupPost');

app/Models/Date.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Date extends Model
{
    protected $fillable = [
        'invoice_id',
        'eta',
        'etb',
        'ets',
        'supply',
        'first_charge',
        'second_charge',
        'third_charge',
        'estimated',
        'payment',
        'payment_date',
        'hour',
    ];

    /**
     * Relationship with Invoice Model
     */
    public function invoice()
    {
        return $this->belongsTo('App\Models\Invoice');
    }

    /**
     * Set date to format yyyy-mm-dd
     */
    public function setEtaAttribute($value)
    {
        if (empty($value)) {
            $this->attributes['eta'] = NULL;
        } else {
            $this->attributes['eta'] = \DateTime::createFromFormat('d/m/Y', $value);
        }
    }

    public function setEtbAttribute($value)
    {
        if (empty($value)) {
            $this->attributes['etb'] = NULL;
        } else {
            $this->attributes['etb'] = \DateTime::createFromFormat('d/m/Y', $value);
        }
    }

    public function setEtsAttribute($value)
    {
        if (empty($value)) {
            $this->attributes['ets'] = NULL;
        } else {
            $this->attributes['ets'] = \DateTime::createFromFormat('d/m/Y', $value);
        }
    }

    public function setFirstChargeAttribute($value)
    {
        if (empty($value)) {
            $this->attributes['first_charge'] = NULL;
        } else {
            $this->attributes['first_charge'] = \DateTime::createFromFormat('d/m/Y', $value);
        }
    }

    public function setSecondChargeAttribute($value)
    {
        if (empty($value)) {
            $this->attributes['second_charge'] = NULL;
        } else {
            $this->attributes['second_charge'] = \DateTime::createFromFormat('d/m/Y', $value);
        }
    }

    public function setThirdChargeAttribute($value)
    {
        if (empty($value)) {
            $this->attributes['third_charge'] = NULL;
        } else {
            $this->attributes['third_charge'] = \DateTime::createFromFormat('d/m/Y', $value);
        }
    }

    public function setSupplyAttribute($value)
    {
        if (empty($value)) {
            $this->attributes['supply'] = NULL;
        } else {
            $this->attributes['supply'] = \DateTime::createFromFormat('d/m/Y', $value);
        }
    }

    public function setEstimatedAttribute($value)
    {
        if (empty($value)) {
            $this->attributes['estimated'] = NULL;
        } else {
            $this->attributes['estimated'] = \DateTime::createFromFormat('d/m/Y', $value);
        }
    }

    public function setPaymentDateAttribute($value)
    {
        if (empty($value)) {
            $this->attributes['payment_date'] = NULL;
        } else {
            $this->attributes['payment_date'] = \DateTime::createFromFormat('d/m/Y', $value);
        }
    }


    /**
     * Return null or formated date time
     */
    public function getEtaAttribute($value)
    {
        return  $value ? date('d/m/Y', strtotime($value)) : NULL;
    }

    public function getEtbAttribute($value)
    {
        return  $value ? date('d/m/Y', strtotime($value)) : NULL;
    }

    public function getEtsAttribute($value)
    {
        return  $value ? date('d/m/Y', strtotime($value)) : NULL;
    }

    public function getFirstChargeAttribute($value)
    {
        return  $value ? date('d/m/Y', strtotime($value)) : NULL;
    }

    public function getSecondChargeAttribute($value)
    {
        return  $value ? date('d/m/Y', strtotime($value)) : NULL;
    }

    public function getThirdChargeAttribute($value)
    {
        return  $value ? date('d/m/Y', strtotime($value)) : NULL;
    }

    public function getSupplyAttribute($value)
    {
        return  $value ? date('d/m/Y', strtotime($value)) : NULL;
    }

    public function getEstimatedAttribute($value)
    {
        return  $value ? date('d/m/Y', strtotime($value)) : NULL;
    }

    public function getPaymentDateAttribute($value)
    {
        return  $value ? date('d/m/Y', strtotime($value)) : NULL;
    }

    /**
     * Return the First Chat
     */
    public function getFirstChatAttribute($value)
    {
        if($this->payment_date) return $this->payment_date;


        $supply  = $this->attributes['supply'];
        $payment = $this->attributes['payment'];

        return  date('d/m/Y', strtotime("$supply + $payment days"));
    }

}

app/Http/Controllers/ApprovalController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Approval\UpdateApprovalRequest;

use App\Models\Agency;
use App\Models\Conclusion;
use App\Models\Invoice;
use App\Models\Port;
use App\Models\Rda;
use App\Models\Status;
use App\Models\Vessel;
use Gate;
use Vinkla\Hashids\Facades\Hashids;

class ApprovalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::denies('approval')) {
            return redirect(route('home'));
        }

        // Get all invoices to line-up approval
        $invoiceLs = Invoice::where('stage', '=', 2)
                            ->where('locale_id', '=', auth()->user()->locale_id)
                            ->get();

        // Get all invoices to Billing approval
        $invoiceBs = Invoice::where('stage', '=', 4)->get();

        return view('approval.index', compact('invoiceLs', 'invoiceBs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int                       $id
     * @return \Illuminate\Http\Response
     */
    public function lineUp($id)
    {
        if (Gate::denies('approval')) {
            return redirect(route('home'));
        }

        $invoice = Invoice::findOrFail(Hashids::decode($id)[0]);

        if ($invoice->stage != 2) {
            return redirect()->back();
        }

        // Check if User locale is the same of the invoice
        if ($invoice->locale_id != auth()->user()->locale_id) {
            return redirect()->back();
        }

        $data = [
            'invoice'  => $invoice,
            'rdas'     => Rda::All()->sortBy('name'),
            'vessels'  => Vessel::All()->sortBy('name'),
            'agencies' => Agency::where('locale_id', '=', $invoice->locale_id)
                                ->orderBy('name')
                                ->get(),
            'ports'    => Port::where('locale_id', '=', $invoice->locale_id)
                              ->orderBy('name')
                              ->get(),
            'conclusions' => Conclusion::All(),
        ];

        return view('approval.line-up')->with($data);

        // solicitação do lorran, p/ padronizar os layouts
        // se invoice->rda->type == 0 (COB) já pode dar baixa diretamente, pula 1 etapa
        // então basta eu alterar apenas a view
        if ($invoice->rda->type == 0) {
            return view('billing.edit')->with($data);
        } else {
            return view('approval.line-up')->with($data);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int                       $id
     * @return \Illuminate\Http\Response
     */
    public function billing($id)
    {
        if (Gate::denies('approval')) {
            return redirect(route('home'));
        }

        $invoice = Invoice::findOrFail(Hashids::decode($id)[0]);

        // Send back if is wrong stage
        if ($invoice->stage != 4) {
            return redirect()->back();
        }

        $data = [
            'invoice'  => $invoice,
            'rdas'     => Rda::All()->sortBy('name'),
            'vessels'  => Vessel::All()->sortBy('name'),
            'agencies' => Agency::where('locale_id', '=', $invoice->locale_id)
                                ->orderBy('name')
                                ->get(),
            'ports'    => Port::where('locale_id', '=', $invoice->locale_id)
                               ->orderBy('name')
                               ->get(),
        ];

        return view('approval.billing')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int                       $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateApprovalRequest $request, $id)
    {
        if (Gate::denies('approval')) {
            return redirect(route('home'));
        }

        $invoice = Invoice::findOrFail($id);
        $value   = $invoice->value;
        $date    = $invoice->date;

        // sempre vai salvar os dados
        $invoice->update($request->all());
        $value->update($request->all());
        $date->update($request->all());

        // altero o conclusion_id se for 2, 3 ou 4
        if (in_array($request->option, [2, 3, 4]) == true) {
            $invoice->conclusion_id = $request->option;
            $invoice->save();
        }

        // approval line-up
        if ($invoice->stage == 2) {
            switch ($request->option) {
                case 'x': // x - update
                    return redirect(route('approval.index'))->with('status', 'Invoice updated with success.');

                    break;
                case 'yes': // approved
                    $invoice->update([
                        'status_id' => 2, // supplied (pois pula processo)
                        'stage'     => 3
                    ]); // mando p/ billing
                    return redirect(route('approval.index'))
                        ->with('status', 'Invoice updated and send to billing with success.');

                    break;
                case 'no': // not approved
                    $invoice->update(['stage'=>1]); // mando p/ line-up
                    return redirect(route('approval.index'))
                        ->with('status', 'Invoice updated and send to line-up with success.');

                    break;
                case '2': //yes
                case '3': //yes with +
                case '4': //yes with -
                    $invoice->update([
                        'stage'     => 4, // mando p/ approval billing
                        'status_id' => 2 // supplied (pois pula processo)
                    ]);

                    return redirect(route('approval.index'))
                        ->with('status', 'Invoice updated and send to approval billing with success.');

                    break;
            }
        }

        // approval billing
        if ($invoice->stage == 4) {
            switch ($request->approval) {
                case 'yes': // approved
                    $invoice->update(['stage' => 5]); // mando p/ historic
                    return redirect(route('approval.index'))
                        ->with('status', 'Invoice updated and send to historic with success.');

                    break;
                case 'no': // not approved
                    $invoice->update(['stage' => 3]); // mando p/ billing
                    return redirect(route('approval.index'))
                        ->with('status', 'Invoice updated and send to billing with success.');

                    break;
                //case 'update': // apenas alterado
            }
        }

        return redirect(route('approval.index'))
            ->with('status', 'Invoice updated with success.');
    }
}

resources/views/approval/index.blade.php
@extends('main')

@section('title', 'Approvals | SGCVS - Sistema de Gestão Comercial Vitória Ship')

@section('navbar')

    @section('module')
        <h3 class="white" style="display: inline-block">
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Approvals
        </h3>
    @endsection

    @include('navbar')

@endsection

@section('content')

    <div class="container-fluid p-t2">
        <div class="row">
            <h3 class="sub-header"> Line-up</h3>
            @include('messages')


            <div class="table-responsive">
                <table id="line-up" class="table table-bordered table-condensed table-hover data-table">
                    <thead>
                        <tr class="active">
                            <th>Supply Date</th>
                            <th>Invoice</th>
                            <th>Vessel</th>
                            <th>Port</th>
                            <th>R.D.A</th>
                            <th>CO-R.D.A</th>
                            <th>Supplied</th>
                            <th class="opcoes">Options</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($invoiceLs as $invoiceL)
                        <tr>
                            <td>{{ $invoiceL->date->supply ?: 'Not supplied' }}</td>
                            <td>{{ $invoiceL->number }}</td>
                            <td>{{ $invoiceL->vessel->name }}</td>
                            <td>{{ $invoiceL->port->name }}</td>
                            <td>{{ $invoiceL->rda->name }}</td>
                            <td>{{ $invoiceL->corda ? $invoiceL->corda->name : '' }}</td>
                            <td>{{ $invoiceL->status->name }}</td>
                            <td>
                                <div class="btn-group btn-group-justified" role="group">
                                    <div class="btn-group btn-group-xs" role="group">
                                        <a href="{{ route('approval.lineUp', Hashids::encode($invoiceL->id)) }}" class="btn btn-default border-right-n loading">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true">
                                        </a>
                                    </div>
                                    <div class="btn-group btn-group-xs" role="group">
                                        <a href="{{ route('invoice.destroy', Hashids::encode($invoiceL->id)) }}" class="btn btn-default"
                                            data-token="{{ csrf_token() }}"
                                            data-request=""
                                            data-title="Are you sure?"
                                            data-message="Are you sure that you want delete this Invoice?"
                                            data-button-text="Yes, delete it!">
                                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="container-fluid p-t2">
        <div class="row">
            <h3 class="sub-header"> Billing</h3>
            <div class="table-responsive">
                <table id="billing" class="table table-bordered table-condensed table-hover data-table">
                    <thead>
                        <tr class="active">
                            <th style="width:1%;">
                                <span class="glyphicon glyphicon-flag"></span>
                            </th>
                            <th style="width:1%;">
                                <span class="glyphicon glyphicon-eye-open"></span>
                            </th>
                            <th style="width:1%;">
                                <span class="glyphicon glyphicon-usd"></span>
                            </th>
                            <th>Suply Date</th>
                            <th>Invoice</th>
                            <th>Vessel</th>
                            <th>Port</th>
                            <th>R.D.A</th>
                            <th>CO-R.D.A</th>
                            <th>Settled</th>
                            <th class="opcoes">Options</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($invoiceBs as $invoiceB)
                        <tr class="alert {{ $invoiceB->lawyer ? 'alert-danger' : '' }} {{ $invoiceB->value->pending_cost ? 'alert-success' : '' }}">
                            <td>
                            @if($invoiceB->date->first_charge)
                                <span class="glyphicon glyphicon-flag"> </span>
                            @endif
                            </td>
                            <td>
                            @if($invoiceB->lawyer)
                                <span class="glyphicon glyphicon-eye-open"> </span>
                            @endif
                            </td>
                            <td>
                            @if($invoiceB->value->pending_cost)
                                <span class="glyphicon glyphicon-usd"> </span>
                            @endif
                            </td>
                            <td>{{ $invoiceB->date->supply }}</td>
                            <td>{{ $invoiceB->number }}</td>
                            <td>{{ $invoiceB->vessel->name }}</td>
                            <td>{{ $invoiceB->port->name }}</td>
                            <td>{{ $invoiceB->rda->name }}</td>
                            <td>{{ $invoiceB->corda ? $invoiceB->corda->name : '' }}</td>

                            <!--<td>{{ strtotime((str_replace('/', '.', $invoiceB->date->first_chat))) < date(strtotime('today')) ? 'YES' : 'NO' }}</td>-->
                            <td>{{ $invoiceB->conclusion->name }}</td>

                            <td>
                                <div class="btn-group btn-group-justified" role="group">
                                    <div class="btn-group btn-group-xs" role="group">
                                        <a href="{{ route('approval.billing', Hashids::encode($invoiceB->id)) }}" class="btn btn-default border-right-n loading">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true">
                                        </a>
                                    </div>
                                    <div class="btn-group btn-group-xs" role="group">
                                        <a href="{{ route('invoice.destroy', $invoiceB->id) }}" class="btn btn-default"
                                            data-token="{{ csrf_token() }}"
                                            data-request=""
                                            data-title="Are you sure?"
                                            data-message="Are you sure that you want delete this Invoice?"
                                            data-button-text="Yes, delete it!">
                                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <span class="alert alert-success" role="info">
                <span class="glyphicon glyphicon-usd" aria-hidden="true"></span>
                Pending Costs
            </span>
            <span class="alert alert-info" role="info">
                <span class="glyphicon glyphicon-flag" aria-hidden="true"></span>
                Charge under process
            </span>
            <span class="alert alert-danger" role="info">
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                Lawyer action
            </span>
        </div>
    </div>
@include('footer')

@endsection